### ISSUE TITLE
Windows executable

### ISSUE THREAD

**Issue by frauschneize** [BartVandewoestyne/oaconvert#144]
Where can I find a compiled windows executable of oaconvert?

I need a tool to convert OpenAir files to KML/KMZ. I don't want to get into coding or compiling.
Thank you.

**Comment by BartVandewoestyne** [comment]
oaconvert currently offers no Windows installers, but I just noticed that each GitHub project has a 'Releases' tab where we can make installers available.  I will try to create one in the near future (without specifying what 'near future' exactly means... I have a busy job too, so give me some time ;-)

**Comment by BartVandewoestyne** [comment]
I have just released v0.1.0 of oaconvert.  You can find the installer under 'releases' tab of the oaconvert project.  Comments are highly appreciated.

**Comment by SkipAir** [comment]
Hello Bart,

I just tried the windows executable. (took some time because I was on Holiday ;-)

Do I understand correctly that the executable only converts from OpenAir to Polish format (and not KML or GPX)? Or am I missing something?

Thanks.
Wim

**Comment by BartVandewoestyne** [comment]
You are missing something.  oaconvert can of course also convert to KML and GPX files.  See https://github.com/BartVandewoestyne/oaconvert/wiki/Using-oaconvert
Use the -o option and specify an output file with a file extension that indicates to what filetype you want to convert the OpenAir file.
